services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql@16/data
    environment:
      POSTGRES_PASSWORD: password
    working_dir: /
    ports:
      - "5432:5432"
  backend:
    build: backend
    image: rails-backend
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  frontend:
    build: frontend
    image: react-frontend
    command: sh -c "yarn install && yarn start && yarn storybook"
    ports:
      - "4000:4000"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    environment:
      POSTGRES_PASSWORD: password
